name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    # TODO: Add rosetta & linux build; and then delete ci.yaml
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: nixci build
